name: GitHub Actions Demo
on: 
  push:
      branches: [main]
  pull_request:
      branches: [main]  
  schedule:
    - cron: '15 6 * * 0'
  workflow_dispatch:
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - run: |
          echo "event: ${{ github.event_name }}"
          echo "branch name ${{ github.ref }}"

      - name: List files in the repository
        run: |
          ls -la
